LOAD DATA
INFILE 'Clientes.dat'
BADFILE 'Clientes.bad'
DISCARDFILE 'Clientes.dsc'
APPEND
INTO TABLE Clientes
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '$$'
TRAILING NULLCOLS
( MSISDN,
  Bono,
  FECHA_UPDATE "SYSDATE"
)
